# we want to make sure it is run on trusty where sudo is provided for postgres
dist: xenial
sudo: true
language: python
matrix:
  include:
  - name: "3.7 Dummy DB"
    python: "3.7"
    env: DATABASE=DUMMY
  - name: "3.7 PG"
    python: "3.7"
    env: DATABASE=postgresql

services:
  - postgresql
  - redis-server
  - docker
# make sure we're on the latest version of postgresql
addons:
  postgresql: "10"
before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install flake8
  - pip install coverage==4.0.3
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  # - pip install guillotina_linkintegrity
  - python setup.py develop
script:
  - flake8 guillotina --config=setup.cfg
  - pytest -s --cov=guillotina_cms -v --cov-report term-missing guillotina_cms
after_success:
  - pip install coveralls
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t plone/guillotina_cms:master .;
    echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME"  --password-stdin;
    docker push plone/guillotina_cms:master;
    fi
