---
aiohttp_settings:
  client_max_size: 20971520
databases:
- db:
    storage: cockroach
    transaction_strategy: dbresolve_readcommitted
    dsn: postgresql://root@cockroachdb:26257/guillotina?sslmode=disable
    read_only: false
    pool_size: 100
applications:
- guillotina_swagger
- guillotina_cms
- guillotina_elasticsearch
- guillotina_rediscache
address: 8081
static:
- favicon.png: static/favicon.png
- swagger_static: guillotina_swagger:static
# - pastanaga: pastanaga-angular/dist
# - ng: plone-angular-demo/dist
# - plone: plone-react
root_user:
  password: root
auth_token_validators:
- guillotina.auth.validators.SaltedHashPasswordValidator
- guillotina_cms.validator.CMSJWTValidator
redis:
  host: "redis"
  port: 6379
jwt:
  secret: secret
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
cors:
  allow_origin:
  - "*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - OPTIONS
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
elasticsearch:
  bulk_size: 20
  index_name_prefix: plone-
  connection_settings:
    hosts:
    - elasticsearch:9200
    sniffer_timeout: 0.5
  index: {}
  mapping_overrides:
    "*": {}
utilities:
- provides: guillotina.async_util.IQueueUtility
  factory: guillotina.async_util.QueueUtility
  settings: {}
- provides: guillotina_cms.interfaces.IWorkflowUtility
  factory: guillotina_cms.utilities.workflow.WorkflowUtility
  settings: {}
- provides: guillotina_cms.interfaces.IPubSubUtility
  factory: guillotina_cms.utilities.pubsub.PubSubUtility
  settings: {}
search_parser: guillotina_cms.search.parser.Parser
workflows:
  basic:
    initial_state: private
    states:
      private:
        actions:
            publish:
                to: public
                check_permission: guillotina.AccessContent
      public:
        triggers:
            set_permission:
                roleperm:
                    role: guillotina.Member
                    perm: guillotina.ViewContent
        actions:
            retire:
                to: private
                check_permission: guillotina.AccessContent
workflows_content:
  guillotina.interfaces.IResource: basic
  guillotina_cms.content.document.IDocument: basic
