description: Guillotina CMS
name: guillotina-cms
sources:
- https://github.com/plone/guillotina_cms
icon: https://avatars0.githubusercontent.com/u/72034?s=200&v=4
maintainers:
- name: Ramon Navarro
  email: ramon@plone.org
version: 0.0.1
